# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flicsy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  

  # Pods for flicsy
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'

  target 'flicsyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flicsyUITests' do
    # Pods for testing
  end

end
